CREATE DATABASE EstagioOF;
USE EstagioOF;

CREATE TABLE usuario(
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(200) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
funcao ENUM ('ADMIN', 'RT', 'GERENTE') NOT NULL
);

CREATE TABLE usuarioRT(
idUsuarioRT INT PRIMARY KEY,
CONSTRAINT fkUsuarioRT
FOREIGN KEY (idUsuarioRT)
REFERENCES usuario(idUsuario));

CREATE TABLE usuarioGerente(
idUsuarioGerente INT PRIMARY KEY,
CONSTRAINT fkUsuarioGerente
FOREIGN KEY (idUsuarioGerente)
REFERENCES usuario(idUsuario));

CREATE TABLE colaborador(
idColaborador INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(200) NOT NULL,
email VARCHAR(100) NOT NULL UNIQUE,
fkRT INT NOT NULL,
fkGerente INT NOT NULL,
CONSTRAINT fkUsuario_RT
FOREIGN KEY (fkRT)
REFERENCES usuarioRT(idUsuarioRT),
CONSTRAINT fkUsuario_Gerente
FOREIGN KEY (fkGerente)
REFERENCES usuarioGerente(idUsuarioGerente));

CREATE TABLE ordemFabricacao(
idOrdem INT PRIMARY KEY AUTO_INCREMENT,
descricao VARCHAR(500) NOT NULL,
status ENUM('PENDENTE_CADASTRAMENTO', 'INICIADA', 'VALIDADA') NOT NULL DEFAULT 'PENDENTE_CADASTRAMENTO',
criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
fkColaborador INT NOT NULL,
CONSTRAINT fkOrdem_Colaborador
FOREIGN KEY (fkColaborador)
REFERENCES colaborador(idColaborador));